language: python

python:
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"

install:
  # install deps
  - pip install -r requirements.txt
  - pip install pytest-cov mock assertpy codacy-coverage
  - pip list

script:
  - py.test -v --cov netboot_config --cov-report xml

after_success:
  - python-codacy-coverage -r coverage.xml
